# Generated by Django 5.1 on 2025-06-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tl_approval', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('perfomed_by', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='employee.employee')),
            ],
        ),
    ]
