# Generated by Django 5.1 on 2025-06-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='perfomed_by',
            new_name='performed_by',
        ),
    ]
