# Generated by Django 5.1 on 2025-06-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_employee_alter_feedback_manager_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='manager_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tl_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
