# Generated by Django 5.1 on 2025-06-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_role'),
        ('feedback', '0004_alter_feedback_manager_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='manager_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tl_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
