# Generated by Django 5.1 on 2025-06-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
