# Generated by Django 5.1 on 2025-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_rating_feedback_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Reason',
            new_name='ReasonManager',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ReasonTL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
