# Generated by Django 5.1 on 2025-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_reason_feedback_reasonmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='last_modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_modified_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
