# Generated by Django 5.1 on 2025-07-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskdetails_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='taskdetails',
            name='team_lead',
        ),
    ]
