# Generated by Django 5.1 on 2025-07-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_password'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='Discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='employee',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='developers',
            field=models.ManyToManyField(related_name='developer_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='testers',
            field=models.ManyToManyField(related_name='tester_projects', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='start_date',
            field=models.DateField(),
        ),
    ]
