# Generated by Django 5.1 on 2025-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_discription_projectdetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
