# Generated by Django 5.1 on 2025-07-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_employee_password'),
        ('task', '0003_remove_taskdetails_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened'), ('Closed', 'Closed')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(related_name='developer_tasks', to='employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='task.taskdetails')),
            ],
        ),
    ]
