# Generated by Django 5.1 on 2025-07-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('employee', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugdetails',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task', to='employee.employee'),
        ),
    ]
