# Generated by Django 5.1 on 2025-07-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bughistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bughistory',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='bughistory',
            name='tester',
        ),
        migrations.AddField(
            model_name='bughistory',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='bughistory',
            name='role',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
