# Generated by Django 5.1 on 2025-07-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_remove_bughistory_developer_remove_bughistory_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bughistory',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=200),
        ),
    ]
