# Generated by Django 5.1 on 2025-07-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_bugimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugImage',
        ),
    ]
