# Generated by Django 5.1 on 2025-07-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_delete_bugimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bug_images/')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bugs.bugdetails')),
            ],
        ),
    ]
