# Generated by Django 5.1 on 2025-07-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_bugimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugHistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bug_history_images/')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bugs.bughistory')),
            ],
        ),
    ]
