# Generated by Django 5.1 on 2025-07-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_bughistoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bughistoryimage',
            old_name='history',
            new_name='bug_history',
        ),
    ]
