# Generated by Django 5.1 on 2025-06-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Causal', 'Causal'), ('Sick', 'Sick'), ('Emergency', 'Emergency'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('number_of_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee.employee')),
            ],
        ),
    ]
